config/routes.rb
Rails.application.routes.draw do

  localized do
    devise_for :administrators, path: :admin, controllers: { registrations: 'admin/registrations' }
    devise_for :councillors, path: :panel

    namespace :admin do
      resources :administrators do
        patch :unlock
      end

      resources :plenary_sessions do
        scope module: :plenary_sessions do
          resources :session_managements, only: [:index] do
            post :check_members_attendance, on: :collection
          end
        end
      end

      resources :polls, only: [:create] do
        patch :stop, on: :member
        patch :vote_as_president, on: :member
      end

      resources :councillors_queues, only: [:create] do
        patch :stop, on: :member
      end

      resources :countdowns, only: [:create] do
        patch :stop, on: :member
      end

      resources :roles, :councillors, :parties, :session_items
      resources :subscriptions, only: [:update]

      root 'home#index'
    end

    namespace :panel do
      resources :plenary_sessions, only: [] do
        scope module: :plenary_sessions do
          resources :councillors_queues, only: [:update]
          resources :polls, only: [:update]
          resources :subscriptions, only: [:create, :destroy]
        end
      end

      root 'home#index'
    end

    scope module: :public do
      resources :plenary_sessions, only: [:show]
      root 'home#index'
    end
  end
end

app/models/councillor.rb
class Councillor < ApplicationRecord
  include Utils::Searching
  devise :database_authenticatable, :validatable, authentication_keys: [:username]
  acts_as_paranoid

  belongs_to :party
  has_many :subscriptions

  validates :name, :username, :party, presence: true
  validates :username, uniqueness: { case_sensitive: false }, format: { with: /\A[[:alnum:]]+\z/, message: I18n.t('errors.custom_messages.only_alphanumeric') }

  searching :name, :username

  scope :active, -> { where(is_active: true) }
  scope :holder, -> { where(is_holder: true) }
  scope :surrogate, -> { where(is_holder: false) }

  scope :by_party, -> (party) {
    where(party_id: party.try(:id) || party) if party.present?
  }

  scope :by_active, -> (is_active) {
    where(is_active: is_active.to_s == 'true') if !is_active.nil? && is_active.to_s.present?
  }

  scope :by_holder, -> (is_holder) {
    where(is_holder: is_holder.to_s == 'true') if !is_holder.nil? && is_holder.to_s.present?
  }

  def email_required?
    false
  end

  def email_changed?
    false
  end
end

app/controllers/admin/councillors_controller.rb
class Admin::CouncillorsController < Admin::BaseController
  before_action :set_councillor, only: [:show, :edit, :update]

  def index
    respond_to do |format|
      format.html { render :index }
      format.json do
        @councillors = scope_for_ng_table(Councillor)
                      .includes(:party)
                      .search(params[:filter].try(:[], :search_query).to_s)
                      .by_party(params[:filter].try(:[], :party_id).to_s)
                      .by_active(params[:filter].try(:[], :is_active).to_s)
                      .by_holder(params[:filter].try(:[], :is_holder).to_s)
      end
    end
  end

  def new
    @councillor = Councillor.new
  end

  def create
    @councillor = Councillor.new(councillor_params)
    @councillor.save
    respond_with :admin, @councillor
  end

  def update
    @councillor.update(councillor_params)
    respond_with :admin, @councillor
  end

  private

  def set_councillor
    @councillor = Councillor.find(params[:id])
  end

  def councillor_params
    result = params
      .require(:councillor)
      .permit(:name, :username, :password, :password_confirmation, :party_id, :is_active, :is_holder)

      if result[:password].blank?
        result.delete(:password)
        result.delete(:password_confirmation)
      end

    result
  end
end

app/views/admin/councillors/_form.html.erb
<%= simple_form_for([:admin, @councillor], html: { 'ng-submit' => 'submitForm($event, this)' }) do |f| %>

  <div class="form-inputs" ng-init="councillor = <%= @councillor.to_json(only: [:is_holder, :is_active]) %>">
    <div class="row">
      <div class="col-md-6">
        <%= f.input :name, input_html: { autofocus: true } %>
      </div>

      <div class="col-sm-6">
        <%= f.association :party, label_method: -> (party) { "#{party.abbreviation} - #{party.name}" },
              input_html: {chosen: '', 'data-placeholder' => t('activerecord.attributes.councillor.party_id')} %>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-4">
        <%= f.input :username %>
      </div>

      <div class="col-sm-4">
        <%= f.input :password, required: @councillor.new_record?, input_html: (@councillor.persisted? ? {'fake-password' => true} : {}) %>
      </div>

      <div class="col-sm-4">
        <%= f.input :password_confirmation, required: @councillor.new_record?, input_html: (@councillor.persisted? ? {'fake-password' => true} : {}) %>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12">
        <%= f.input :is_holder, input_html: { icheck: '', 'ng-model' => 'councillor.is_holder' } %>
        <%= f.input :is_active, input_html: { icheck: '', 'ng-model' => 'councillor.is_active' } %>
      </div>
    </div>

    <%= f.submit '', class: 'hide' %>
  </div>
<% end %>

app/views/admin/councillors/edit.html.erb
<% content_for :sub_header do %>
  <div class="col-sm-6">
    <h2><%= t("models_and_attributes.models.councillor.other") %></h2>
    <ol class="breadcrumb">
      <li><%= link_to t('page.modules.home'), [:admin, :root] %></li>
      <li><%= link_to t('page.modules.councillors'), [:admin, :councillors] %></li>
      <li class="active">
        <strong><%= t('actions.edit') %></strong>
      </li>
    </ol>
  </div>
  <div class="col-sm-6 text-right">
    <%= link_to [:admin, :councillors], class: 'btn btn-w-s btn-primary m-t-md',
          data: {'form-submit' => url_for([:admin, @councillor])} do %>

      <i class="fa fa-save"></i><br>
      <%= t('buttons.save') %>
    <% end %>
    <%= link_to [:admin, @councillor], class: 'btn btn-w-s btn-warning m-t-md' do %>
      <i class="fa fa-remove"></i><br>
      <%= t('buttons.cancel') %>
    <% end %>
  </div>
<% end %>

<%= flash_messages %>
<div class="row">
  <div class="col-xs-12 current-responsive-padding">
    <div class="ibox float-e-margins">
      <div class="ibox-content protected">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/admin/councillors/index.html.erb
<% content_for :angular_controller, 'CouncillorsController' %>
<% content_for :sub_header do %>
  <div class="col-sm-6">
    <h2><%= t('models_and_attributes.models.councillor.other') %></h2>
    <ol class="breadcrumb">
      <li><%= link_to t('page.modules.home'), [:admin, :root] %></li>
      <li class="active">
        <strong><%= t('page.modules.councillors') %></strong>
      </li>
    </ol>
  </div>
  <div class="col-sm-6 text-right">
    <%= link_to [:new, :admin, :councillor], class: 'btn btn-w-s btn-primary m-t-md' do %>
      <i class="fa fa-plus"></i><br/>
      <%= t('buttons.new') %>
    <% end if can?(:create, Councillor) %>
  </div>
<% end %>

<%= flash_messages %>

<div class="row responsive-padding">
  <div class="col-xs-12" ng-init="init(<%= @config.to_json %>)">
    <div class="ibox float-e-margins">
      <div class="ibox-title">
        <h5>
          <%= t('view.keywords.list') %>&nbsp;&nbsp;&nbsp;
          <big><i class="fa fa-spinner fa-spin text-success" ng-show="tableParams.loadingTable"></i></big>
        </h5>
      </div>

      <div class="ibox-content">
        <form>
          <div class="m-b-lg">
            <div class="row m-b-xss">
              <div class="col-xs-12">
                <small>
                  <a class="pull-right" ng-click="NgTableService.clearFilters(filters)"><%= t('buttons.clear_filters') %></a>
                </small>
              </div>
            </div>

            <div class="form-inputs">
              <div class="row m-b-sm">
                <div class="col-xs-12">
                  <input type="text" id="filter" placeholder="<%= t([:name, :username], scope: [:activerecord, :attributes, :councillor]).join('/') %>"
                      class="form-control input-md" ng-model="filters.search_query" autocomplete="off" autofocus>
                </div>
              </div>

              <div class="row m-b-sm">
                <div class="col-xs-12 col-sm-6 col-md-3 m-t-xs" ng-init="activeStatuses = <%= t('enums.specific_items.councillor.is_active').to_json %>;">
                  <select chosen data-placeholder-text-single="'<%= t('activerecord.attributes.councillor.is_active') %>'"
                          allow-single-deselect="true"
                          class="form-control"
                          ng-model="filters.is_active"
                          ng-options="key as value for (key, value) in activeStatuses">
                    <option></option>
                  </select>
                </div>

                <div class="col-xs-12 col-sm-6 col-md-3 m-t-xs" ng-init="holderStatuses = <%= t('enums.specific_items.councillor.is_holder').to_json %>;">
                  <select chosen data-placeholder-text-single="'<%= t('activerecord.attributes.councillor.is_holder') %>'"
                          allow-single-deselect="true"
                          class="form-control"
                          ng-model="filters.is_holder"
                          ng-options="key as value for (key, value) in holderStatuses">
                    <option></option>
                  </select>
                </div>

                <div class="col-xs-12 col-md-6 m-t-xs">
                  <select chosen data-placeholder-text-single="'<%= t('activerecord.attributes.councillor.party_id') %>'"
                          allow-single-deselect="true"
                          class="form-control"
                          ng-model="filters.party_id"
                          ng-options="party.id as (party.abbreviation + ' - ' + party.name) for party in parties">
                    <option></option>
                  </select>
                </div>
              </div>
            </div>

            <div class="row m-t-sm">
              <div class="col-sm-offset-8 col-sm-4">
                <button class="btn btn-block btn-primary" ng-click="NgTableService.search(filters)" ng-disabled="tableParams.loadingTable">
                  <i class="fa fa-search"></i> <%= t('buttons.search') %>
                </button>
              </div>
            </div>
          </div>
        </form>

        <div class="m-t-md">
          <small class="pull-right text-muted" ng-bind-html="'info.records_found_html' | t:{count: tableParams.total() || 0} | trust"></small><br>
          <hr class="m-t-none">
        </div>

        <%= custom_flash_messages info: {show: true, fixed: true, icon: :info, message: t('info.no_results')}, html: {'ng-hide' => 'tableParams.total() > 0'} %>
        <div class="table-responsive" ng-show="tableParams.total() > 0">
          <div loading-container="tableParams.loadingTable">
            <table ng-table="tableParams" template-pagination="/angular-templates/ng-table/paginate" class="table table-striped table-hover">
              <tr class="vertical-middle" data-href="{{councillor.url}}" ng-repeat="councillor in $data track by councillor.id">

                <td data-title="'<%= t('activerecord.attributes.councillor.name') %>'" data-sortable="'councillors.name'">
                  {{councillor.name}}
                </td>
                <td data-title="'<%= t('activerecord.attributes.councillor.username') %>'" data-sortable="'councillors.username'">
                  {{councillor.username}}
                </td>
                <td data-title="'<%= t('activerecord.attributes.councillor.party_id') %>'" data-sortable="'parties.abbreviation'">
                  {{councillor.party.abbreviation}}
                </td>
                <td data-title="'<%= t('activerecord.attributes.councillor.is_holder') %>'" data-sortable="'councillors.is_holder'">
                  {{holderStatuses[councillor.is_holder]}}
                </td>
                <td data-title="'<%= t('activerecord.attributes.councillor.is_active') %>'" data-sortable="'councillors.is_active'">
                  {{activeStatuses[councillor.is_active]}}
                </td>

              </tr>
            </table>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/admin/councillors/new.html.erb
<% content_for :sub_header do %>
  <div class="col-sm-6">
    <h2><%= t("models_and_attributes.models.councillor.other") %></h2>
    <ol class="breadcrumb">
      <li><%= link_to t('page.modules.home'), [:admin, :root] %></li>
      <li><%= link_to t('page.modules.councillors'), [:admin, :councillors] %></li>
      <li class="active">
        <strong><%= t('actions.new') %></strong>
      </li>
    </ol>
  </div>
  <div class="col-sm-6 text-right">
    <%= link_to '#', class: 'btn btn-w-s btn-primary m-t-md',
          data: {'form-submit' => url_for([:admin, :councillors])} do %>

      <i class="fa fa-save"></i><br/>
      <%= t('buttons.save') %>
    <% end %>
    <%= link_to [:admin, @councillor], class: 'btn btn-w-s btn-warning m-t-md' do %>
      <i class="fa fa-remove"></i><br/>
      <%= t('buttons.cancel') %>
    <% end %>
  </div>
<% end %>

<%= flash_messages %>
<div class="row">
  <div class="col-xs-12 current-responsive-padding">
    <div class="ibox float-e-margins">
      <div class="ibox-content protected">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/admin/councillors/show.html.erb
<% content_for :sub_header do %>
  <div class="col-sm-6">
    <h2><%= t('models_and_attributes.models.councillor.other') %></h2>
    <ol class="breadcrumb">
      <li><%= link_to t('page.modules.home'), [:admin, :root] %></li>
      <li><%= link_to t('page.modules.councillors'), [:admin, :councillors] %></li>
      <li class="active">
        <strong><%= t('actions.show') %></strong>
      </li>
    </ol>
  </div>
  <div class="col-sm-6 text-right">
    <%= link_to [:new, :admin, :councillor], class: 'btn btn-w-s btn-primary m-t-md' do %>
      <i class="fa fa-plus"></i><br/>
      <%= t('buttons.new') %>
    <% end if can?(:create, Councillor) %>

    <%= link_to [:edit, :admin, @councillor], class: 'btn btn-w-s btn-info m-t-md' do %>
      <i class="fa fa-edit"></i><br/>
      <%= t('buttons.edit') %>
    <% end if can?(:update, Councillor) %>

    <%= link_to [:admin, :councillors], class: 'btn btn-w-s btn-white m-t-md m-l-sm' do %>
      <i class="fa fa-reply"></i><br/>
      <%= t('buttons.back') %>
    <% end %>
  </div>
<% end %>

<%= flash_messages %>
<div class="row responsive-padding">
  <div class="col-xs-12">
    <div class="ibox float-e-margins">
      <div class="ibox-title">
        <h5>
          <%= t('view.keywords.informations') %>
        </h5>
      </div>

      <div class="ibox-content">
        <ul class="todo-list">

          <li class="show-action-label">
            <div class="col-sm-3"><%= t('activerecord.attributes.councillor.name') %>:</div>
            <div class="col-sm-9"><%= @councillor.name %></div>
          </li>
          <li class="show-action-label">
            <div class="col-sm-3"><%= t('activerecord.attributes.councillor.party') %>:</div>
            <div class="col-sm-9"><%= link_to "#{@councillor.party.abbreviation} - #{@councillor.party.name}", admin_party_path(@councillor.party) %></div>
          </li>
          <li class="show-action-label">
            <div class="col-sm-3"><%= t('activerecord.attributes.councillor.username') %>:</div>
            <div class="col-sm-9"><%= @councillor.username %></div>
          </li>
          <li class="show-action-label">
            <div class="col-sm-3"><%= t('activerecord.attributes.councillor.is_holder') %></div>
            <div class="col-sm-9"><%= t('enums.items.boolean')[@councillor.is_holder] %></div>
          </li>
          <li class="show-action-label">
            <div class="col-sm-3"><%= t('activerecord.attributes.councillor.is_active') %></div>
            <div class="col-sm-9"><%= t('enums.items.boolean')[@councillor.is_active] %></div>
          </li>

        </ul>
      </div>
    </div>
  </div>
</div>