config/routes.rb
Rails.application.routes.draw do

  localized do
    devise_for :administrators, path: :admin, controllers: { registrations: 'admin/registrations' }
    devise_for :councillors, path: :panel

    namespace :admin do
      resources :administrators do
        patch :unlock
      end

      resources :plenary_sessions do
        scope module: :plenary_sessions do
          resources :session_managements, only: [:index] do
            post :check_members_attendance, on: :collection
          end
        end
      end

      resources :polls, only: [:create] do
        patch :stop, on: :member
        patch :vote_as_president, on: :member
      end

      resources :councillors_queues, only: [:create] do
        patch :stop, on: :member
      end

      resources :countdowns, only: [:create] do
        patch :stop, on: :member
      end

      resources :roles, :councillors, :parties, :session_items
      resources :subscriptions, only: [:update]

      root 'home#index'
    end

    namespace :panel do
      resources :plenary_sessions, only: [] do
        scope module: :plenary_sessions do
          resources :councillors_queues, only: [:update]
          resources :polls, only: [:update]
          resources :subscriptions, only: [:create, :destroy]
        end
      end

      root 'home#index'
    end

    scope module: :public do
      resources :plenary_sessions, only: [:show]
      root 'home#index'
    end
  end
end

app/views/layouts/admin/_header_signed_in.html.erb
<header class="row border-bottom">
  <nav class="navbar navbar-static-top white-bg" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
      <a class="navbar-minimalize minimalize-styl-2 btn btn-primary" href><i class="fa fa-bars"></i> </a>
    </div>
    <ul class="nav navbar-top-links navbar-right user-menu-responsive">

      <li class="visible-xs user-menu-item-responsive">
        <div class="dropdown">
          <a href data-toggle="dropdown" class="dropdown-toggle btn btn-primary">
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu animated fadeInRight user-menu">
            <li>
              <%= link_to edit_registration_path(current_administrator) do %>
                <i class="fa fa-edit"></i> <%= t('profile.edit') %>
              <% end %>
            </li>
            <li class="divider"></li>
            <li>
              <%= link_to destroy_session_path(:administrator), method: :delete,
                  data: {confirm: t('confirm.signout')} do %>
                <i class="fa fa-sign-out"></i> <%= t('profile.signout') %>
              <% end %>
            </li>
          </ul>
        </div>
      </li>

      <li class="hidden-xs">
        <%= link_to destroy_session_path(:administrator), method: :delete, class: 'superior-logout',
            data: {confirm: t('confirm.signout')} do %>
          <i class="fa fa-sign-out"></i> <%= t('profile.signout') %>
        <% end %>
      </li>
    </ul>
  </nav>
</header>

app/views/layouts/admin/_sidemenu.html.erb
<nav class="navbar-default navbar-static-side">
  <div class="sidebar-collapse">
    <ul class="nav metismenu" id="side-menu">
      <li class="nav-header">
        <div class="dropdown profile-element">
          <%= link_to admin_root_path do  %>
            <%= image_tag 'votweb-full.svg', class: 'img-responsive' %>
          <% end %>
          <a href data-toggle="dropdown" class="dropdown-toggle">
            <span class="clear"> <span class="block m-t-sm"> <strong class="font-bold"><%= current_administrator.name %></strong></span>
            <span class="text-muted text-xs block"><%= current_administrator.email %> <b class="caret"></b></span> </span>
          </a>
          <ul class="dropdown-menu animated fadeInRight m-t-xs">
            <li>
              <%= link_to edit_registration_path(current_administrator) do %>
                <i class="fa fa-edit"></i> <%= t('profile.edit') %>
              <% end %>
            </li>
            <li class="divider"></li>
            <li>
              <%= link_to destroy_session_path(:administrator), method: :delete,
                  data: {confirm: t('confirm.signout')} do %>
                <i class="fa fa-sign-out"></i> <%= t('profile.signout') %>
              <% end %>
            </li>
          </ul>
        </div>
      </li>

      <%= content_tag(:li, class: class_for_item_menu('administrators')) do %>
        <%= link_to admin_administrators_path do  %>
          <i class="fa fa-user"></i>
          <span class="nav-label"><%= t('models_and_attributes.models.administrator.other') %></span>
        <% end %>
      <% end if can?(:read, Administrator) %>

      <%= content_tag(:li, class: class_for_item_menu('roles')) do %>
        <%= link_to admin_roles_path do  %>
          <i class="fa fa-check-square-o"></i>
          <span class="nav-label"><%= t('models_and_attributes.models.role.other') %></span>
        <% end %>
      <% end if can?(:read, Role) %>

      <%= content_tag(:li, class: class_for_item_menu('session_items')) do %>
        <%= link_to admin_session_items_path do  %>
          <i class="fa fa-files-o"></i>
          <span class="nav-label"><%= t('models_and_attributes.models.session_item.other') %></span>
        <% end %>
      <% end if can?(:read, SessionItem) %>

      <%= content_tag(:li, class: class_for_item_menu('plenary_sessions')) do %>
        <%= link_to admin_plenary_sessions_path do  %>
          <i class="fa fa-bullhorn"></i>
          <span class="nav-label"><%= t('models_and_attributes.models.plenary_session.other') %></span>
        <% end %>
      <% end if can?(:read, PlenarySession) %>

      <%= content_tag(:li, class: class_for_item_menu('councillors')) do %>
        <%= link_to admin_councillors_path do  %>
          <i class="fa fa-group"></i>
          <span class="nav-label"><%= t('models_and_attributes.models.councillor.other') %></span>
        <% end %>
      <% end if can?(:read, Councillor) %>

      <%= content_tag(:li, class: class_for_item_menu('parties')) do %>
        <%= link_to admin_parties_path do  %>
          <i class="fa fa-flag"></i>
          <span class="nav-label"><%= t('models_and_attributes.models.party.other') %></span>
        <% end %>
      <% end if can?(:read, Party) %>
    </ul>
  </div>
</nav>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.default_locale %>">
  <head>
    <meta charset="utf-8">
    <meta name="turbolinks-cache-control" content="no-cache">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="robots" content="noindex,nofollow">
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <% content_for(:module, t(controller_name, scope: [:page, :modules], default: '')) unless content_for? :module %>
    <title>
      <%= page_title(app_name: t('page.titles.short'), page_title_symbol: :module, separator: ' | ') %>
    </title>

    <%= favicon_link_tag 'favicon.png' %>
    <%= stylesheet_link_tag    'admin/application', media: 'all', 'data-turbolinks-track' => 'reload' %>

    <%= javascript_include_tag 'i18n', 'data-turbolinks-track' => 'reload' %>

    <script type="text/javascript">
      window.I18n.defaultLocale = '<%= I18n.default_locale %>';
      window.I18n.locale = '<%= I18n.locale %>';
      window.I18n.pathLocale = '<%= I18n.locale.to_s.underscore %>';
    </script>

    <%= javascript_include_tag 'admin/application', 'data-turbolinks-track' => 'reload' %>
  </head>

  <%= content_for?(:content) ? yield(:content) : yield %>
</html>

app/views/layouts/admin/authenticated.html.erb
<%= content_for :content do %>
  <body class="<%= body_class %>" <%= raw(content_for?(:angular_controller) ? "ng-controller=\'#{content_for(:angular_controller)}\'" : '') %>>
    <%= render partial: 'layouts/admin/sidemenu' %>

    <div id="page-wrapper" class="gray-bg">
      <%= render partial: 'layouts/admin/header_signed_in' %>

      <% if content_for?(:sub_header) %>
        <div class="row wrapper border-bottom white-bg page-heading">
          <%= yield(:sub_header) %>
        </div>
      <% end %>

      <div class="wrapper wrapper-content">
        <%= yield %>
      </div>

      <footer class="footer">
        <%= t('page.footers.short_html', app: t('app.name'), year: Date.today.year) %>
      </footer>
    </div>
  </body>
<% end %>

<%= render file: 'layouts/admin/application' %>