config/routes.rb
Rails.application.routes.draw do

  localized do
    devise_for :administrators, path: :admin, controllers: { registrations: 'admin/registrations' }
    devise_for :councillors, path: :panel

    namespace :admin do
      resources :administrators do
        patch :unlock
      end

      resources :plenary_sessions do
        scope module: :plenary_sessions do
          resources :session_managements, only: [:index] do
            post :check_members_attendance, on: :collection
          end
        end
      end

      resources :polls, only: [:create] do
        patch :stop, on: :member
        patch :vote_as_president, on: :member
      end

      resources :councillors_queues, only: [:create] do
        patch :stop, on: :member
      end

      resources :countdowns, only: [:create] do
        patch :stop, on: :member
      end

      resources :roles, :councillors, :parties, :session_items
      resources :subscriptions, only: [:update]

      root 'home#index'
    end

    namespace :panel do
      resources :plenary_sessions, only: [] do
        scope module: :plenary_sessions do
          resources :councillors_queues, only: [:update]
          resources :polls, only: [:update]
          resources :subscriptions, only: [:create, :destroy]
        end
      end

      root 'home#index'
    end

    scope module: :public do
      resources :plenary_sessions, only: [:show]
      root 'home#index'
    end
  end
end

app/models/session_item.rb
class SessionItem < ApplicationRecord
  include Utils::Searching
  acts_as_paranoid

  belongs_to :author, class_name: 'Councillor', foreign_key: :councillor_id
  belongs_to :session, class_name: 'PlenarySession', foreign_key: :plenary_session_id

  enum acceptance: [:not_voted, :approved, :rejected]

  searching :title, :abstract

  scope :by_acceptance, -> (acceptance) {
    where(acceptance: acceptances[acceptance]) if acceptance.present?
  }

  validates :title, :abstract, :acceptance, presence: true
end

app/controllers/admin/session_items_controller.rb
class Admin::SessionItemsController < Admin::BaseController
  before_action :set_session_item, only: [:show, :edit, :update, :destroy]

  def index
    respond_to do |format|
      format.html { render :index }
      format.json do
        @session_items = scope_for_ng_table(SessionItem)
                            .includes(:author)
                            .search(params[:filter].try(:[], :search_query).to_s)
                            .by_acceptance(params[:filter].try(:[], :acceptance).to_s)
      end
    end
  end

  def new
    @session_item = SessionItem.new
  end

  def create
    @session_item = SessionItem.new(session_item_params)
    @session_item.save
    respond_with :admin, @session_item
  end

  def update
    @session_item.update(session_item_params)
    respond_with :admin, @session_item
  end

  def destroy
    @session_item.destroy
    respond_with @session_item, location: -> { admin_session_items_path }
  end

  private

  def set_session_item
    @session_item = SessionItem.find(params[:id])
  end

  def session_item_params
    params
      .require(:session_item)
      .permit(:title, :abstract, :councillor_id, :acceptance)
  end
end

app/views/admin/session_items/_form.html.erb
<%= simple_form_for([:admin, @session_item]) do |f| %>

  <div class="form-inputs">
    <div class="row">
      <div class="col-xs-12">
        <%= f.input :title, input_html: { autofocus: true } %>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12 col-md-8">
        <%= f.association :author, collection: Councillor.active, label_method: :name,
            input_html: {chosen: '', 'data-placeholder' => t('activerecord.attributes.session_item.author'), 'allow-single-deselect' => 'true'} %>
      </div>

      <div class="col-xs-12 col-md-4">
        <%= f.input :acceptance,
                    collection: t('enums.specific_items.session_item.acceptance').invert,
                    include_blank: true,
                    input_html: {chosen: '', 'data-placeholder' => t('activerecord.attributes.session_item.acceptance')} %>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12">
        <%= f.input :abstract, as: :text, input_html: { class: 'resize-vertical', rows: 3 } %>
      </div>
    </div>

    <%= f.submit '', class: 'hide' %>
  </div>
<% end %>

app/views/admin/session_items/edit.html.erb
<% content_for :sub_header do %>
  <div class="col-sm-6">
    <h2><%= t("models_and_attributes.models.session_item.other") %></h2>
    <ol class="breadcrumb">
      <li><%= link_to t('page.modules.home'), [:admin, :root] %></li>
      <li><%= link_to t('page.modules.session_items'), [:admin, :session_items] %></li>
      <li class="active">
        <strong><%= t('actions.edit') %></strong>
      </li>
    </ol>
  </div>
  <div class="col-sm-6 text-right">
    <%= link_to [:admin, :session_items], class: 'btn btn-w-s btn-primary m-t-md',
          data: {'form-submit' => url_for([:admin, @session_item])} do %>

      <i class="fa fa-save"></i><br>
      <%= t('buttons.save') %>
    <% end %>
    <%= link_to [:admin, @session_item], class: 'btn btn-w-s btn-warning m-t-md' do %>
      <i class="fa fa-remove"></i><br>
      <%= t('buttons.cancel') %>
    <% end %>
  </div>
<% end %>

<%= flash_messages %>
<div class="row">
  <div class="col-xs-12 current-responsive-padding">
    <div class="ibox float-e-margins">
      <div class="ibox-content protected">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/admin/session_items/index.html.erb
<% content_for :angular_controller, 'SessionItemsController' %>
<% content_for :sub_header do %>
  <div class="col-sm-6">
    <h2><%= t('models_and_attributes.models.session_item.other') %></h2>
    <ol class="breadcrumb">
      <li><%= link_to t('page.modules.home'), [:admin, :root] %></li>
      <li class="active">
        <strong><%= t('page.modules.session_items') %></strong>
      </li>
    </ol>
  </div>
  <div class="col-sm-6 text-right">
    <%= link_to [:new, :admin, :session_item], class: 'btn btn-w-s btn-primary m-t-md' do %>
      <i class="fa fa-plus"></i><br/>
      <%= t('buttons.new') %>
    <% end if can?(:create, SessionItem) %>
  </div>
<% end %>

<%= flash_messages %>

<div class="row responsive-padding">
  <div class="col-xs-12" ng-init="init(<%= @config.to_json %>)">
    <div class="ibox float-e-margins">
      <div class="ibox-title">
        <h5>
          <%= t('view.keywords.list') %>&nbsp;&nbsp;&nbsp;
          <big><i class="fa fa-spinner fa-spin text-success" ng-show="tableParams.loadingTable"></i></big>
        </h5>
      </div>

      <div class="ibox-content">
        <form>
          <div class="m-b-lg">
            <div class="row m-b-xss">
              <div class="col-xs-12">
                <small>
                  <a class="pull-right" ng-click="NgTableService.clearFilters(filters)"><%= t('buttons.clear_filters') %></a>
                </small>
              </div>
            </div>

            <div class="form-inputs">
              <div class="row m-b-sm">
                <div class="col-xs-12 col-sm-8 m-t-xs">
                  <input type="text" id="filter" placeholder="<%= t([:title, :abstract], scope: [:activerecord, :attributes, :session_item]).join('/') %>"
                      class="form-control input-md" ng-model="filters.search_query" autocomplete="off" autofocus>
                </div>

                <div class="col-xs-12 col-sm-4 m-t-xs" ng-init="acceptances = <%= t('enums.specific_items.session_item.acceptance').to_json %>;">
                  <select chosen data-placeholder-text-single="'<%= t('activerecord.attributes.session_item.acceptance') %>'"
                          allow-single-deselect="true"
                          class="form-control"
                          ng-model="filters.acceptance"
                          ng-options="key as value for (key, value) in acceptances">
                    <option></option>
                  </select>
                </div>
              </div>
            </div>

            <div class="row m-t-sm">
              <div class="col-sm-offset-8 col-sm-4">
                <button class="btn btn-block btn-primary" ng-click="NgTableService.search(filters)" ng-disabled="tableParams.loadingTable">
                  <i class="fa fa-search"></i> <%= t('buttons.search') %>
                </button>
              </div>
            </div>
          </div>
        </form>

        <div class="m-t-md">
          <small class="pull-right text-muted" ng-bind-html="'info.records_found_html' | t:{count: tableParams.total() || 0} | trust"></small><br>
          <hr class="m-t-none">
        </div>

        <%= custom_flash_messages info: {show: true, fixed: true, icon: :info, message: t('info.no_results')}, html: {'ng-hide' => 'tableParams.total() > 0'} %>
        <div class="table-responsive" ng-show="tableParams.total() > 0">
          <div loading-container="tableParams.loadingTable">
            <table ng-table="tableParams" template-pagination="/angular-templates/ng-table/paginate" class="table table-striped table-hover">
              <tr data-href="{{session_item.url}}" ng-repeat="session_item in $data track by session_item.id">

                <td data-title="'<%= t('activerecord.attributes.session_item.title') %>'" data-sortable="'session_items.title'">
                  {{session_item.title}}
                </td>
                <td data-title="'<%= t('activerecord.attributes.session_item.author') %>'" data-sortable="'councillors.name'">
                  {{session_item.author}}
                </td>
                <td data-title="'<%= t('activerecord.attributes.session_item.abstract') %>'" data-sortable="'session_items.abstract'">
                  <span ng-bind-html="(session_item.abstract || '').replace('\n', '<br>') | trust"></span>
                </td>
                <td data-title="'<%= t('activerecord.attributes.session_item.created_at') %>'" data-sortable="'session_items.created_at'">
                  {{session_item.created_at | date:'medium'}}
                </td>
                <td data-title="'<%= t('activerecord.attributes.session_item.acceptance') %>'" data-sortable="'session_items.acceptance'">
                  {{acceptances[session_item.acceptance]}}
                </td>

              </tr>
            </table>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/admin/session_items/new.html.erb
<% content_for :sub_header do %>
  <div class="col-sm-6">
    <h2><%= t("models_and_attributes.models.session_item.other") %></h2>
    <ol class="breadcrumb">
      <li><%= link_to t('page.modules.home'), [:admin, :root] %></li>
      <li><%= link_to t('page.modules.session_items'), [:admin, :session_items] %></li>
      <li class="active">
        <strong><%= t('actions.new') %></strong>
      </li>
    </ol>
  </div>
  <div class="col-sm-6 text-right">
    <%= link_to '#', class: 'btn btn-w-s btn-primary m-t-md',
          data: {'form-submit' => url_for([:admin, :session_items])} do %>

      <i class="fa fa-save"></i><br/>
      <%= t('buttons.save') %>
    <% end %>
    <%= link_to [:admin, @session_item], class: 'btn btn-w-s btn-warning m-t-md' do %>
      <i class="fa fa-remove"></i><br/>
      <%= t('buttons.cancel') %>
    <% end %>
  </div>
<% end %>

<%= flash_messages %>
<div class="row">
  <div class="col-xs-12 current-responsive-padding">
    <div class="ibox float-e-margins">
      <div class="ibox-content protected">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/admin/session_items/show.html.erb
<% content_for :sub_header do %>
  <div class="col-sm-6">
    <h2><%= t('models_and_attributes.models.session_item.other') %></h2>
    <ol class="breadcrumb">
      <li><%= link_to t('page.modules.home'), [:admin, :root] %></li>
      <li><%= link_to t('page.modules.session_items'), [:admin, :session_items] %></li>
      <li class="active">
        <strong><%= t('actions.show') %></strong>
      </li>
    </ol>
  </div>
  <div class="col-sm-6 text-right">
    <%= link_to [:new, :admin, :session_item], class: 'btn btn-w-s btn-primary m-t-md' do %>
      <i class="fa fa-plus"></i><br/>
      <%= t('buttons.new') %>
    <% end if can?(:create, SessionItem) %>

    <%= link_to [:edit, :admin, @session_item], class: 'btn btn-w-s btn-info m-t-md' do %>
      <i class="fa fa-edit"></i><br/>
      <%= t('buttons.edit') %>
    <% end if can?(:update, SessionItem) %>

    <%= link_to [:admin, @session_item], class: 'btn btn-w-s btn-danger m-t-md',
          method: :delete, data: {confirm: t('confirm.delete_record')} do %>
      <i class="fa fa-trash"></i><br/>
      <%= t('buttons.destroy') %>
    <% end if can?(:destroy, SessionItem) %>

    <%= link_to [:admin, :session_items], class: 'btn btn-w-s btn-white m-t-md m-l-sm' do %>
      <i class="fa fa-reply"></i><br/>
      <%= t('buttons.back') %>
    <% end %>
  </div>
<% end %>

<%= flash_messages %>
<div class="row responsive-padding">
  <div class="col-xs-12">
    <div class="ibox float-e-margins">
      <div class="ibox-title">
        <h5>
          <%= t('view.keywords.informations') %>
        </h5>
      </div>

      <div class="ibox-content">
        <ul class="todo-list">

          <li class="show-action-label">
            <div class="col-sm-3"><%= t('activerecord.attributes.session_item.title') %>:</div>
            <div class="col-sm-9"><%= @session_item.title %></div>
          </li>
          <li class="show-action-label">
            <div class="col-sm-3"><%= t('activerecord.attributes.session_item.acceptance') %>:</div>
            <div class="col-sm-9"><%= t(@session_item.acceptance, scope: [:enums, :specific_items, :session_item, :acceptance]) %></div>
          </li>
          <li class="show-action-label">
            <div class="col-sm-3"><%= t('activerecord.attributes.session_item.author') %>:</div>
            <div class="col-sm-9">
              <% if @session_item.author.present? %>
                <%= link_to @session_item.author.name, admin_councillor_path(@session_item.author) %>
              <% else %>
                <span class="text-muted"><%= t('miscellaneous.session_item.no_author') %></span>
              <% end %>
            </div>
          </li>
          <li class="show-action-label">
            <div class="col-sm-3"><%= t('activerecord.models.plenary_session.one') %>:</div>
            <div class="col-sm-9">
              <% if @session_item.session.present? %>
                <%= link_to(@session_item.session.title, admin_plenary_session_path(@session_item.session)) %>
              <% else %>
                <span class="text-muted"><%= t('miscellaneous.session_item.no_session') %></span>
              <% end %>
            </div>
          </li>
          <li class="show-action-label">
            <div class="col-sm-3"><%= t('activerecord.attributes.session_item.abstract') %>:</div>
            <div class="col-sm-9"><%= sanitize @session_item.abstract.to_s.gsub("\n", "<br>"), allow: %w(br) %></div>
          </li>

        </ul>
      </div>
    </div>
  </div>
</div>